CREATE TABLE TEMPLATE (
                          ID INT,
                          NAME VARCHAR(50)
);

INSERT INTO TEMPLATE (ID, NAME) VALUES (0, 'TEST');
INSERT INTO TEMPLATE (ID, NAME) VALUES (1, 'TEST');